# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from lightgbm import LGBMClassifier

from sklearn.metrics import roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.inspection import permutation_importance
from sklearn.model_selection import StratifiedKFold, cross_val_score
from feature_engine.selection import DropFeatures

## Utils

In [2]:
def dump_pickle(file_obj, file_path):
    with open(file_path, 'bw') as file:
        pickle.dump(file_obj, file)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/X_train.parquet')
X_test = pd.read_parquet('../data/X_test.parquet')

y_train = pd.read_parquet('../data/y_train.parquet')

In [4]:
X_train.head()

,ordinal_encoder__compound,target_encoder__driver,target_encoder__compound,target_encoder__race,standard_scaler__lapnumber,standard_scaler__position,standard_scaler__raceprogress,standard_scaler__year,robust_scaler__position_change,robust_scaler__cumulative_degradation,...,remainder__fuzzy_1_position_position_change,remainder__fuzzy_2_position_position_change,remainder__fuzzy_3_position_position_change,remainder__fuzzy_0_raceprogress_lapnumber,remainder__fuzzy_1_raceprogress_lapnumber,remainder__fuzzy_2_raceprogress_lapnumber,remainder__lap_time_inv,remainder__position_norm,remainder__is_pit_lap,remainder__race_progress_sin
id,,,,,,,,,,,,,,,,,,,,,
0,0.50,0.203815,0.328482,0.154734,1.585901,-0.308849,1.487008,-1.486487,1.666667,1.040769,...,0.947453,0.005655,0.020178,0.000549,0.997580,0.001872,0.012740,0.40,0,0.781831
1,0.50,0.199575,0.327181,0.176114,0.229628,-1.066602,0.033534,1.440545,-1.000000,-5.009333,...,0.074107,0.081854,0.098684,0.015175,0.007697,0.977128,0.013316,0.20,1,0.885456
2,0.50,0.218840,0.326837,0.187526,2.116616,0.638343,1.902200,-1.486487,1.000000,-1.970285,...,0.226475,0.059038,0.614716,0.024077,0.912645,0.063278,0.014095,0.65,0,0.537300
3,0.25,0.200526,0.100888,0.145166,-1.244581,-0.498287,-1.029455,-0.510810,0.000000,0.338641,...,0.088099,0.041344,0.113803,0.950726,0.010153,0.039121,0.010598,0.35,0,0.239316
4,0.50,0.192082,0.327657,0.214557,0.170660,-1.445478,0.092589,-1.486487,1.000000,0.169816,...,0.256086,0.040890,0.083385,0.009589,0.004844,0.985566,0.009270,0.10,1,0.906308

In [5]:
X_test.head()

,ordinal_encoder__compound,target_encoder__driver,target_encoder__compound,target_encoder__race,standard_scaler__lapnumber,standard_scaler__position,standard_scaler__raceprogress,standard_scaler__year,robust_scaler__position_change,robust_scaler__cumulative_degradation,...,remainder__fuzzy_1_position_position_change,remainder__fuzzy_2_position_position_change,remainder__fuzzy_3_position_position_change,remainder__fuzzy_0_raceprogress_lapnumber,remainder__fuzzy_1_raceprogress_lapnumber,remainder__fuzzy_2_raceprogress_lapnumber,remainder__lap_time_inv,remainder__position_norm,remainder__is_pit_lap,remainder__race_progress_sin
id,,,,,,,,,,,,,,,,,,,,,
439140,0.25,0.182308,0.101132,0.133462,-0.124182,-1.066602,0.261317,-0.510810,0.000000,0.396609,...,0.001144,0.000465,0.000894,0.067702,0.028176,0.904122,0.010708,0.20,0,0.954721
439141,0.25,0.356316,0.101132,0.150547,0.052723,-1.634917,0.300590,-0.510810,0.000000,0.470778,...,0.081596,0.033933,0.053686,0.019477,0.011500,0.969023,0.011005,0.05,0,0.963550
439142,0.25,0.121796,0.101132,0.133462,0.052723,0.259466,0.489100,-0.510810,0.000000,0.301036,...,0.087683,0.072629,0.701444,0.038897,0.031448,0.929655,0.010768,0.55,0,0.992709
439143,0.00,0.198847,0.193475,0.253713,-1.008708,1.017219,-1.025511,0.464868,0.333333,0.724449,...,0.023113,0.022859,0.935769,0.984826,0.002887,0.012287,0.010530,0.75,0,0.242362
439144,0.50,0.197127,0.327536,0.114051,1.703838,0.448905,1.518343,0.464868,2.333333,0.003617,...,0.718809,0.040632,0.151701,0.002043,0.991340,0.006618,0.010090,0.60,0,0.766044

# Machine Learning

## Base

In [12]:
cv_results = cross_val_score(
    estimator=LGBMClassifier(random_state=42, verbose=0, class_weight='balanced'), 
    X=X_train, 
    y=y_train.PitNextLap, 
    scoring='roc_auc', 
    cv=StratifiedKFold(random_state=42, shuffle=True), 
    n_jobs=-1
)

In [13]:
cv_results.mean()

np.float64(0.9431221232074156)

## Feature Selection

In [14]:
model = LGBMClassifier(random_state=42, verbose=0, class_weight='balanced')
model.fit(X_train, y_train.PitNextLap)

LGBMClassifier(class_weight='balanced', random_state=42, verbose=0)

In [15]:
perm_result = permutation_importance(
    estimator=model, 
    X=X_train, 
    y=y_train.PitNextLap, 
    n_jobs=-1, 
    scoring='roc_auc'
)


importance_df = pd.DataFrame({
    "feature": X_train.columns.tolist(),
    "importance_mean": perm_result.importances_mean,
    "importance_std": perm_result.importances_std
}).sort_values(by="importance_mean", ascending=False)

In [16]:
importance_df.query("importance_mean <= 0").feature.tolist()

['remainder__stint_low',
 'remainder__lapnumber_low',
 'remainder__lapnumber_high',
 'remainder__stint_high',
 'remainder__position_high',
 'remainder__position_low',
 'remainder__is_pit_lap']

In [17]:
drop_feat = DropFeatures(features_to_drop=importance_df.query("importance_mean <= 0").feature.tolist())

## Fine Tuning

In [18]:
def objective(trial, X, y):

    lgbm = LGBMClassifier(
        objective='binary',
        metric='auc',
        boosting_type='gbdt',
        num_leaves=trial.suggest_int('num_leaves', 16, 256),
        max_depth=trial.suggest_int('max_depth', 3, 12),
        learning_rate=trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        lambda_l1=trial.suggest_float('lambda_l1', 1e-3, 10.0, log=True),
        lambda_l2=trial.suggest_float('lambda_l2', 1e-3, 10.0, log=True),
        feature_fraction=trial.suggest_float('feature_fraction', 0.6, 1.0),
        bagging_fraction=trial.suggest_float('bagging_fraction', 0.6, 1.0),
        bagging_freq=trial.suggest_int('bagging_freq', 1, 7),
        min_child_samples=trial.suggest_int('min_child_samples', 10, 100),
        verbosity=-1,
        n_estimators=2000,
        random_state=42
    )
    
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    aucs = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]
        
        model = Pipeline([('drop_feat', drop_feat), ('lgbm', lgbm)])
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]
        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

study = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=50, n_jobs=-1, show_progress_bar=True)

[I 2026-05-05 10:50:07,551] A new study created in memory with name: no-name-d76049e0-e543-49e0-96d8-84406ee2dcc5

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-05 10:58:31,408] Trial 4 finished with value: 0.9419877041418276 and parameters: {'num_leaves': 239, 'max_depth': 3, 'learning_rate': 0.030730577802823324, 'lambda_l1': 2.209216819030977, 'lambda_l2': 8.50513565498258, 'feature_fraction': 0.6581182538436924, 'bagging_fraction': 0.6439052883733097, 'bagging_freq': 3, 'min_child_samples': 67}. Best is trial 4 with value: 0.9419877041418276.
[I 2026-05-05 10:58:57,320] Trial 2 finished with value: 0.9438548406434911 and parameters: {'num_leaves': 164, 'max_depth': 3, 'learning_rate': 0.06484882631434648, 'lambda_l1': 0.21698736848017378, 'lambda_l2': 0.021944996621324306, 'feature_fraction': 0.6815360766797781, 'bagging_fraction': 0.8118826595671834, 'bagging_freq': 6, 'min_child_samples': 10}. Best is trial 2 with value: 0.9438548406434911.
[I 2026-05-05 10:59:22,582] Trial 10 finished with value: 0.9437597697804009 and parameters: {'num_leaves': 160, 'max_depth': 3, 'learning_rate': 0.07465680314668285, 'lambda_l1': 0.18285331276236244, 'lambda_l2': 0.08717486386278434, 'feature_fraction': 0.8608546292909864, 'bagging_fraction': 0.6202183094243282, 'bagging_freq': 7, 'min_child_samples': 51}. Best is trial 2 with value: 0.9438548406434911.
[I 2026-05-05 11:08:22,045] Trial 6 finished with value: 0.9467473598334983 and parameters: {'num_leaves': 35, 'max_depth': 12, 'learning_rate': 0.011504102327416482, 'lambda_l1': 0.01385748261368671, 'lambda_l2': 0.0030338117352258403, 'feature_fraction': 0.7080287099677138, 'bagging_fraction': 0.62559417374417, 'bagging_freq': 1, 'min_child_samples': 96}. Best is trial 6 with value: 0.9467473598334983.
[I 2026-05-05 11:09:26,402] Trial 11 finished with value: 0.947803565435646 and parameters: {'num_leaves': 109, 'max_depth': 6, 'learning_rate': 0.031090932982502536, 'lambda_l1': 8.13666330600903, 'lambda_l2': 6.440288516937021, 'feature_fraction': 0.6242573906352685, 'bagging_fraction': 0.638494817905229, 'bagging_freq': 3, 'min_child_samples': 83}. Best is trial 11 with value: 0.947803565435646.
[I 2026-05-05 11:10:32,392] Trial 14 finished with value: 0.9450888688651673 and parameters: {'num_leaves': 51, 'max_depth': 4, 'learning_rate': 0.12326120451633124, 'lambda_l1': 0.012928585678390758, 'lambda_l2': 0.009694407930177345, 'feature_fraction': 0.8171880767686036, 'bagging_fraction': 0.6850697216736672, 'bagging_freq': 5, 'min_child_samples': 27}. Best is trial 11 with value: 0.947803565435646.
[I 2026-05-05 11:11:52,649] Trial 1 finished with value: 0.9471460507718051 and parameters: {'num_leaves': 198, 'max_depth': 6, 'learning_rate': 0.04238004633478416, 'lambda_l1': 0.09613380419242061, 'lambda_l2': 0.0033027244746911206, 'feature_fraction': 0.9695981648508802, 'bagging_fraction': 0.8643085170223785, 'bagging_freq': 7, 'min_child_samples': 42}. Best is trial 11 with value: 0.947803565435646.
[I 2026-05-05 11:12:14,179] Trial 9 finished with value: 0.9473443508488678 and parameters: {'num_leaves': 136, 'max_depth': 6, 'learning_rate': 0.03835953523730866, 'lambda_l1': 0.006355639732005772, 'lambda_l2': 0.004025204678969999, 'feature_fraction': 0.9701824130691309, 'bagging_fraction': 0.833218543182256, 'bagging_freq': 4, 'min_child_samples': 73}. Best is trial 11 with value: 0.947803565435646.
[I 2026-05-05 11:13:33,768] Trial 3 pruned.
[I 2026-05-05 11:13:37,792] Trial 8 pruned.
[I 2026-05-05 11:18:19,639] Trial 13 finished with value: 0.9469275999245165 and parameters: {'num_leaves': 130, 'max_depth': 6, 'learning_rate': 0.01405512350106095, 'lambda_l1': 2.320950796994651, 'lambda_l2': 0.010764646658256704, 'feature_fraction': 0.7885208180252888, 'bagging_fraction': 0.6025085689948705, 'bagging_freq': 7, 'min_child_samples': 29}. Best is trial 11 with value: 0.947803565435646.
[I 2026-05-05 11:19:43,516] Trial 19 pruned.
[I 2026-05-05 11:20:36,413] Trial 15 pruned.
[I 2026-05-05 11:21:37,768] Trial 7 pruned.
[I 2026-05-05 11:22:23,518] Trial 0 finished with value: 0.948056393329028 and parameters: {'num_leaves': 115, 'max_depth': 12, 'learning_rate': 0.026746388554621872, 'lambda_l1': 0.0019228762704597397, 'lambda_l2': 0.0844647298963208, 'feature_fraction': 0.9857628446220462, 'bagging_fraction': 0.8915709563908352, 'bagging_freq': 6, 'min_child_samples': 25}. Best is trial 0 with value: 0.948056393329028.
[I 2026-05-05 11:24:10,992] Trial 18 finished with value: 0.946028765337077 and parameters: {'num_leaves': 125, 'max_depth': 4, 'learning_rate': 0.05924859410534798, 'lambda_l1': 0.0036795239640860355, 'lambda_l2': 4.758846026816204, 'feature_fraction': 0.8056329021045073, 'bagging_fraction': 0.7577497493775041, 'bagging_freq': 5, 'min_child_samples': 17}. Best is trial 0 with value: 0.948056393329028.
[I 2026-05-05 11:24:27,052] Trial 17 finished with value: 0.9475696962511584 and parameters: {'num_leaves': 24, 'max_depth': 8, 'learning_rate': 0.059791863832238175, 'lambda_l1': 0.010272785062743747, 'lambda_l2': 1.4345539494901847, 'feature_fraction': 0.7299955173921293, 'bagging_fraction': 0.8258621424356116, 'bagging_freq': 7, 'min_child_samples': 72}. Best is trial 0 with value: 0.948056393329028.
[I 2026-05-05 11:25:56,262] Trial 20 pruned.
[I 2026-05-05 11:33:26,557] Trial 12 finished with value: 0.9463035990705126 and parameters: {'num_leaves': 170, 'max_depth': 9, 'learning_rate': 0.06653156723108579, 'lambda_l1': 0.03535108234192854, 'lambda_l2': 0.60120024589944, 'feature_fraction': 0.6190227107479654, 'bagging_fraction': 0.9238652581950785, 'bagging_freq': 4, 'min_child_samples': 78}. Best is trial 0 with value: 0.948056393329028.
[I 2026-05-05 11:36:20,615] Trial 5 finished with value: 0.9464763524747379 and parameters: {'num_leaves': 194, 'max_depth': 12, 'learning_rate': 0.04897858319470589, 'lambda_l1': 0.00964951141629778, 'lambda_l2': 0.010569494085846934, 'feature_fraction': 0.9728854316829743, 'bagging_fraction': 0.791553239914282, 'bagging_freq': 1, 'min_child_samples': 99}. Best is trial 0 with value: 0.948056393329028.
[I 2026-05-05 11:44:26,575] Trial 21 finished with value: 0.9488056338536766 and parameters: {'num_leaves': 79, 'max_depth': 9, 'learning_rate': 0.017096201708847198, 'lambda_l1': 8.521635216354115, 'lambda_l2': 0.5800858065101456, 'feature_fraction': 0.602983327904544, 'bagging_fraction': 0.9889630462066024, 'bagging_freq': 3, 'min_child_samples': 77}. Best is trial 21 with value: 0.9488056338536766.
[I 2026-05-05 11:46:46,988] Trial 24 finished with value: 0.9484782149582847 and parameters: {'num_leaves': 94, 'max_depth': 8, 'learning_rate': 0.02089742469536595, 'lambda_l1': 0.002562455520426998, 'lambda_l2': 0.0010417723092563441, 'feature_fraction': 0.6015795997506087, 'bagging_fraction': 0.6994261020878394, 'bagging_freq': 3, 'min_child_samples': 75}. Best is trial 21 with value: 0.9488056338536766.
[I 2026-05-05 11:47:23,404] Trial 25 finished with value: 0.9484466222295005 and parameters: {'num_leaves': 94, 'max_depth': 8, 'learning_rate': 0.022061643516795598, 'lambda_l1': 0.0012153221993887026, 'lambda_l2': 0.0010907373010848056, 'feature_fraction': 0.6158506822054005, 'bagging_fraction': 0.7045536837371924, 'bagging_freq': 3, 'min_child_samples': 74}. Best is trial 21 with value: 0.9488056338536766.
[I 2026-05-05 11:47:33,360] Trial 16 finished with value: 0.9485943971763288 and parameters: {'num_leaves': 145, 'max_depth': 9, 'learning_rate': 0.019107655833543055, 'lambda_l1': 0.0022156153757446227, 'lambda_l2': 0.018066420657142725, 'feature_fraction': 0.9090055491671643, 'bagging_fraction': 0.9391532454958421, 'bagging_freq': 1, 'min_child_samples': 66}. Best is trial 21 with value: 0.9488056338536766.
[I 2026-05-05 11:47:47,926] Trial 23 finished with value: 0.9486472785136375 and parameters: {'num_leaves': 93, 'max_depth': 8, 'learning_rate': 0.021859804349953393, 'lambda_l1': 0.0011430656243826749, 'lambda_l2': 0.26074265664467416, 'feature_fraction': 0.6000267523917034, 'bagging_fraction': 0.9824899764789463, 'bagging_freq': 3, 'min_child_samples': 75}. Best is trial 21 with value: 0.9488056338536766.
[I 2026-05-05 11:51:09,787] Trial 26 finished with value: 0.9482000519124505 and parameters: {'num_leaves': 86, 'max_depth': 9, 'learning_rate': 0.023205203456537326, 'lambda_l1': 0.0017836516900304686, 'lambda_l2': 0.0975101780684357, 'feature_fraction': 0.915393086812696, 'bagging_fraction': 0.9186169483345837, 'bagging_freq': 3, 'min_child_samples': 15}. Best is trial 21 with value: 0.9488056338536766.
[I 2026-05-05 11:51:31,324] Trial 29 finished with value: 0.948712933699467 and parameters: {'num_leaves': 93, 'max_depth': 9, 'learning_rate': 0.021991463709760368, 'lambda_l1': 0.0020243928158622695, 'lambda_l2': 0.09736336080556549, 'feature_fraction': 0.60954128072492, 'bagging_fraction': 0.9282042958443653, 'bagging_freq': 3, 'min_child_samples': 38}. Best is trial 21 with value: 0.9488056338536766.
[I 2026-05-05 11:51:51,350] Trial 22 finished with value: 0.9479294060379448 and parameters: {'num_leaves': 94, 'max_depth': 8, 'learning_rate': 0.026178676891310867, 'lambda_l1': 0.0025294415409234067, 'lambda_l2': 0.7310070299853917, 'feature_fraction': 0.9787476872390344, 'bagging_fraction': 0.9730164631196404, 'bagging_freq': 3, 'min_child_samples': 74}. Best is trial 21 with value: 0.9488056338536766.
[I 2026-05-05 11:54:38,288] Trial 28 finished with value: 0.9490573487343728 and parameters: {'num_leaves': 87, 'max_depth': 9, 'learning_rate': 0.021000691458317493, 'lambda_l1': 6.500852759023503, 'lambda_l2': 0.06673211954364124, 'feature_fraction': 0.6040099173775758, 'bagging_fraction': 0.9280987419355077, 'bagging_freq': 3, 'min_child_samples': 35}. Best is trial 28 with value: 0.9490573487343728.
[I 2026-05-05 11:55:26,927] Trial 27 finished with value: 0.9489760162481437 and parameters: {'num_leaves': 83, 'max_depth': 9, 'learning_rate': 0.021429652738319344, 'lambda_l1': 9.954402319838541, 'lambda_l2': 0.060881282568509665, 'feature_fraction': 0.602287860120045, 'bagging_fraction': 0.9462081407251426, 'bagging_freq': 3, 'min_child_samples': 61}. Best is trial 28 with value: 0.9490573487343728.
[I 2026-05-05 12:05:59,325] Trial 31 finished with value: 0.9481327488830956 and parameters: {'num_leaves': 93, 'max_depth': 10, 'learning_rate': 0.02301325268090379, 'lambda_l1': 0.0010762186473348724, 'lambda_l2': 0.09513424232718826, 'feature_fraction': 0.9165620333734931, 'bagging_fraction': 0.6958996646564428, 'bagging_freq': 3, 'min_child_samples': 39}. Best is trial 28 with value: 0.9490573487343728.
[I 2026-05-05 12:12:00,137] Trial 34 finished with value: 0.9485414844163795 and parameters: {'num_leaves': 84, 'max_depth': 9, 'learning_rate': 0.01748004724536817, 'lambda_l1': 0.0013551623637025956, 'lambda_l2': 0.0011236941807596578, 'feature_fraction': 0.6104390333929213, 'bagging_fraction': 0.6933683848174934, 'bagging_freq': 2, 'min_child_samples': 61}. Best is trial 28 with value: 0.9490573487343728.
[I 2026-05-05 12:13:58,343] Trial 30 finished with value: 0.948350369666661 and parameters: {'num_leaves': 93, 'max_depth': 10, 'learning_rate': 0.022291644939097275, 'lambda_l1': 8.302606093640302, 'lambda_l2': 0.10472027313229625, 'feature_fraction': 0.9192997449088809, 'bagging_fraction': 0.7112859116715622, 'bagging_freq': 3, 'min_child_samples': 40}. Best is trial 28 with value: 0.9490573487343728.
[I 2026-05-05 12:17:21,916] Trial 32 finished with value: 0.9491158111292952 and parameters: {'num_leaves': 91, 'max_depth': 10, 'learning_rate': 0.02162240100181007, 'lambda_l1': 8.586251928219816, 'lambda_l2': 0.13521544596587384, 'feature_fraction': 0.6167724746065923, 'bagging_fraction': 0.9804947200290441, 'bagging_freq': 3, 'min_child_samples': 86}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:18:44,824] Trial 33 finished with value: 0.9481925471753868 and parameters: {'num_leaves': 87, 'max_depth': 10, 'learning_rate': 0.018537991767761792, 'lambda_l1': 0.0012286185191441232, 'lambda_l2': 0.1343022101986881, 'feature_fraction': 0.908798341386951, 'bagging_fraction': 0.9828664997784515, 'bagging_freq': 2, 'min_child_samples': 40}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:19:32,894] Trial 36 finished with value: 0.9478963589504996 and parameters: {'num_leaves': 76, 'max_depth': 10, 'learning_rate': 0.016957358187735333, 'lambda_l1': 0.001073193128842747, 'lambda_l2': 0.18091117646171023, 'feature_fraction': 0.919966384482569, 'bagging_fraction': 0.9970313106480566, 'bagging_freq': 2, 'min_child_samples': 60}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:19:40,757] Trial 35 finished with value: 0.9482064853443241 and parameters: {'num_leaves': 87, 'max_depth': 10, 'learning_rate': 0.019717480585608474, 'lambda_l1': 0.0028052404700714627, 'lambda_l2': 0.04500545117696417, 'feature_fraction': 0.9109806659927779, 'bagging_fraction': 0.9897585417671254, 'bagging_freq': 2, 'min_child_samples': 59}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:22:35,312] Trial 39 finished with value: 0.9487090247385112 and parameters: {'num_leaves': 74, 'max_depth': 10, 'learning_rate': 0.015427395427907085, 'lambda_l1': 5.343464647836343, 'lambda_l2': 0.21168799479577413, 'feature_fraction': 0.6562567052645129, 'bagging_fraction': 0.9602173231617952, 'bagging_freq': 2, 'min_child_samples': 37}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:23:16,329] Trial 37 finished with value: 0.9486674853331257 and parameters: {'num_leaves': 75, 'max_depth': 10, 'learning_rate': 0.016925479931042757, 'lambda_l1': 9.836066663012069, 'lambda_l2': 0.029595066874341908, 'feature_fraction': 0.6556459314544445, 'bagging_fraction': 0.998444333694037, 'bagging_freq': 2, 'min_child_samples': 59}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:23:35,739] Trial 38 finished with value: 0.948535647207931 and parameters: {'num_leaves': 72, 'max_depth': 9, 'learning_rate': 0.016188876802506674, 'lambda_l1': 8.05835334057573, 'lambda_l2': 0.1969917717296873, 'feature_fraction': 0.6531561373075486, 'bagging_fraction': 0.9896981617599854, 'bagging_freq': 2, 'min_child_samples': 40}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:24:27,950] Trial 41 finished with value: 0.9486567988938905 and parameters: {'num_leaves': 68, 'max_depth': 10, 'learning_rate': 0.016547380944259168, 'lambda_l1': 8.923044058616075, 'lambda_l2': 0.04329334201737184, 'feature_fraction': 0.6494316614032309, 'bagging_fraction': 0.874494350595057, 'bagging_freq': 4, 'min_child_samples': 58}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:26:28,404] Trial 40 finished with value: 0.9485970490908052 and parameters: {'num_leaves': 67, 'max_depth': 10, 'learning_rate': 0.015969328824417525, 'lambda_l1': 8.186485599497148, 'lambda_l2': 0.035608688360982056, 'feature_fraction': 0.6611351733263423, 'bagging_fraction': 0.8688197346731553, 'bagging_freq': 2, 'min_child_samples': 37}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:32:40,270] Trial 42 finished with value: 0.9486588850734383 and parameters: {'num_leaves': 69, 'max_depth': 10, 'learning_rate': 0.01579460392011955, 'lambda_l1': 8.538570066015499, 'lambda_l2': 0.04181188478314912, 'feature_fraction': 0.6455992687334993, 'bagging_fraction': 0.951153594533836, 'bagging_freq': 2, 'min_child_samples': 38}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:35:30,394] Trial 43 finished with value: 0.9487010218538756 and parameters: {'num_leaves': 68, 'max_depth': 10, 'learning_rate': 0.016287711575380944, 'lambda_l1': 7.209244181752789, 'lambda_l2': 0.03718951276614971, 'feature_fraction': 0.6431035333492379, 'bagging_fraction': 0.8771279967157045, 'bagging_freq': 2, 'min_child_samples': 38}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:36:14,349] Trial 44 finished with value: 0.9486437026114081 and parameters: {'num_leaves': 67, 'max_depth': 10, 'learning_rate': 0.015372588345926315, 'lambda_l1': 4.2441831117382485, 'lambda_l2': 0.04131383002900868, 'feature_fraction': 0.6428407435130731, 'bagging_fraction': 0.8674145086659907, 'bagging_freq': 2, 'min_child_samples': 46}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:38:30,948] Trial 45 finished with value: 0.9486436831099091 and parameters: {'num_leaves': 68, 'max_depth': 10, 'learning_rate': 0.01548388480811463, 'lambda_l1': 5.318222527394422, 'lambda_l2': 0.0412369554424274, 'feature_fraction': 0.6542498498427296, 'bagging_fraction': 0.9549285984574171, 'bagging_freq': 2, 'min_child_samples': 88}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:38:41,550] Trial 46 finished with value: 0.9486292610801914 and parameters: {'num_leaves': 67, 'max_depth': 11, 'learning_rate': 0.014555109120514038, 'lambda_l1': 4.425238159454815, 'lambda_l2': 0.03907048259079142, 'feature_fraction': 0.6511738756742029, 'bagging_fraction': 0.8727250159100847, 'bagging_freq': 2, 'min_child_samples': 89}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:39:02,903] Trial 48 finished with value: 0.9482612605740307 and parameters: {'num_leaves': 65, 'max_depth': 11, 'learning_rate': 0.011261292087403046, 'lambda_l1': 4.6754156328684715, 'lambda_l2': 0.047404528506162225, 'feature_fraction': 0.6552268307903721, 'bagging_fraction': 0.8755484291352742, 'bagging_freq': 4, 'min_child_samples': 91}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:39:05,881] Trial 47 finished with value: 0.9482179864190918 and parameters: {'num_leaves': 67, 'max_depth': 11, 'learning_rate': 0.010440422744843823, 'lambda_l1': 4.674992837445127, 'lambda_l2': 0.026303584910208275, 'feature_fraction': 0.6495053235863012, 'bagging_fraction': 0.8862649529608952, 'bagging_freq': 4, 'min_child_samples': 88}. Best is trial 32 with value: 0.9491158111292952.
[I 2026-05-05 12:39:10,969] Trial 49 finished with value: 0.9479322474057847 and parameters: {'num_leaves': 58, 'max_depth': 11, 'learning_rate': 0.010455553437889238, 'lambda_l1': 4.508827046235009, 'lambda_l2': 0.051802766575104235, 'feature_fraction': 0.6487660076833813, 'bagging_fraction': 0.8751727827274988, 'bagging_freq': 4, 'min_child_samples': 90}. Best is trial 32 with value: 0.9491158111292952.

In [19]:
model_tuned = LGBMClassifier(
    objective='binary',
    metric='auc',
    boosting_type='gbdt',
    verbosity=-1,
    n_estimators=2000,
    random_state=42,
    **study.best_params
)

pipe_tuned = Pipeline([('drop_feat', drop_feat), ('lgbm', model_tuned)])
pipe_tuned.fit(X_train, y_train.PitNextLap)

Pipeline(steps=[('drop_feat',
                 DropFeatures(features_to_drop=['remainder__stint_low',
                                                'remainder__lapnumber_low',
                                                'remainder__lapnumber_high',
                                                'remainder__stint_high',
                                                'remainder__position_high',
                                                'remainder__position_low',
                                                'remainder__is_pit_lap'])),
                ('lgbm',
                 LGBMClassifier(bagging_fraction=0.9804947200290441,
                                bagging_freq=3,
                                feature_fraction=0.6167724746065923,
                                lambda_l1=8.586251928219816,
                                lambda_l2=0.13521544596587384,
                                learning_rate=0.02162240100181007, max_depth=10,
                                metric='auc', min_child_samples=86,
                                n_estimators=2000, num_leaves=91,
                                objective='binary', random_state=42,
                                verbosity=-1))])

# Deploy

In [20]:
dump_pickle(pipe_tuned, '../models/model_lightgbm.pkl')