# Imports

In [21]:
import os
import optuna
import pickle

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from xgboost import XGBClassifier

from sklearn.metrics import roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.inspection import permutation_importance
from sklearn.model_selection import cross_val_score, StratifiedKFold

from feature_engine.selection import DropFeatures

In [2]:
os.environ["XGBOOST_VERBOSITY"] = "0"

## Utils

In [3]:
def dump_pickle(file_obj, file_path):
    with open(file_path, 'bw') as file:
        pickle.dump(file_obj, file)

# Loading Dataset

In [4]:
X_train = pd.read_parquet('../data/X_train.parquet')
X_test = pd.read_parquet('../data/X_test.parquet')

y_train = pd.read_parquet('../data/y_train.parquet')

In [5]:
X_train.head()

,ordinal_encoder__compound,target_encoder__driver,target_encoder__compound,target_encoder__race,standard_scaler__lapnumber,standard_scaler__position,standard_scaler__raceprogress,standard_scaler__year,robust_scaler__position_change,robust_scaler__cumulative_degradation,...,remainder__fuzzy_1_position_position_change,remainder__fuzzy_2_position_position_change,remainder__fuzzy_3_position_position_change,remainder__fuzzy_0_raceprogress_lapnumber,remainder__fuzzy_1_raceprogress_lapnumber,remainder__fuzzy_2_raceprogress_lapnumber,remainder__lap_time_inv,remainder__position_norm,remainder__is_pit_lap,remainder__race_progress_sin
id,,,,,,,,,,,,,,,,,,,,,
0,0.50,0.203815,0.328482,0.154734,1.585901,-0.308849,1.487008,-1.486487,1.666667,1.040769,...,0.947453,0.005655,0.020178,0.000549,0.997580,0.001872,0.012740,0.40,0,0.781831
1,0.50,0.199575,0.327181,0.176114,0.229628,-1.066602,0.033534,1.440545,-1.000000,-5.009333,...,0.074107,0.081854,0.098684,0.015175,0.007697,0.977128,0.013316,0.20,1,0.885456
2,0.50,0.218840,0.326837,0.187526,2.116616,0.638343,1.902200,-1.486487,1.000000,-1.970285,...,0.226475,0.059038,0.614716,0.024077,0.912645,0.063278,0.014095,0.65,0,0.537300
3,0.25,0.200526,0.100888,0.145166,-1.244581,-0.498287,-1.029455,-0.510810,0.000000,0.338641,...,0.088099,0.041344,0.113803,0.950726,0.010153,0.039121,0.010598,0.35,0,0.239316
4,0.50,0.192082,0.327657,0.214557,0.170660,-1.445478,0.092589,-1.486487,1.000000,0.169816,...,0.256086,0.040890,0.083385,0.009589,0.004844,0.985566,0.009270,0.10,1,0.906308

In [6]:
X_test.head()

,ordinal_encoder__compound,target_encoder__driver,target_encoder__compound,target_encoder__race,standard_scaler__lapnumber,standard_scaler__position,standard_scaler__raceprogress,standard_scaler__year,robust_scaler__position_change,robust_scaler__cumulative_degradation,...,remainder__fuzzy_1_position_position_change,remainder__fuzzy_2_position_position_change,remainder__fuzzy_3_position_position_change,remainder__fuzzy_0_raceprogress_lapnumber,remainder__fuzzy_1_raceprogress_lapnumber,remainder__fuzzy_2_raceprogress_lapnumber,remainder__lap_time_inv,remainder__position_norm,remainder__is_pit_lap,remainder__race_progress_sin
id,,,,,,,,,,,,,,,,,,,,,
439140,0.25,0.182308,0.101132,0.133462,-0.124182,-1.066602,0.261317,-0.510810,0.000000,0.396609,...,0.001144,0.000465,0.000894,0.067702,0.028176,0.904122,0.010708,0.20,0,0.954721
439141,0.25,0.356316,0.101132,0.150547,0.052723,-1.634917,0.300590,-0.510810,0.000000,0.470778,...,0.081596,0.033933,0.053686,0.019477,0.011500,0.969023,0.011005,0.05,0,0.963550
439142,0.25,0.121796,0.101132,0.133462,0.052723,0.259466,0.489100,-0.510810,0.000000,0.301036,...,0.087683,0.072629,0.701444,0.038897,0.031448,0.929655,0.010768,0.55,0,0.992709
439143,0.00,0.198847,0.193475,0.253713,-1.008708,1.017219,-1.025511,0.464868,0.333333,0.724449,...,0.023113,0.022859,0.935769,0.984826,0.002887,0.012287,0.010530,0.75,0,0.242362
439144,0.50,0.197127,0.327536,0.114051,1.703838,0.448905,1.518343,0.464868,2.333333,0.003617,...,0.718809,0.040632,0.151701,0.002043,0.991340,0.006618,0.010090,0.60,0,0.766044

## Columns

In [7]:
X_train.columns

Index(['ordinal_encoder__compound', 'target_encoder__driver',
       'target_encoder__compound', 'target_encoder__race',
       'standard_scaler__lapnumber', 'standard_scaler__position',
       'standard_scaler__raceprogress', 'standard_scaler__year',
       'robust_scaler__position_change',
       'robust_scaler__cumulative_degradation', 'robust_scaler__laptime_delta',
       'robust_scaler__laptime_s', 'robust_scaler__stint',
       'robust_scaler__driver_mean_lap', 'robust_scaler__tyrelife',
       'robust_scaler__delta_x_tyre_life', 'robust_scaler__compound_tyre_life',
       'robust_scaler__stint_progress', 'robust_scaler__tyre_life_ratio',
       'robust_scaler__degradation_per_lap',
       'robust_scaler__position_change_cum', 'robust_scaler__laps_since_pit',
       'remainder__pitstop', 'remainder__lapnumber_low',
       'remainder__lapnumber_medium', 'remainder__lapnumber_high',
       'remainder__stint_low', 'remainder__stint_medium',
       'remainder__stint_high', 'remainder__position_low',
       'remainder__position_medium', 'remainder__position_high',
       'remainder__laptime_s_low', 'remainder__laptime_s_medium',
       'remainder__laptime_s_high', 'remainder__raceprogress_low',
       'remainder__raceprogress_medium', 'remainder__raceprogress_high',
       'remainder__fuzzy_0_laptime_s_laptime_delta',
       'remainder__fuzzy_1_laptime_s_laptime_delta',
       'remainder__fuzzy_2_laptime_s_laptime_delta',
       'remainder__fuzzy_3_laptime_s_laptime_delta',
       'remainder__fuzzy_4_laptime_s_laptime_delta',
       'remainder__fuzzy_5_laptime_s_laptime_delta',
       'remainder__fuzzy_0_tyrelife_cumulative_degradation',
       'remainder__fuzzy_1_tyrelife_cumulative_degradation',
       'remainder__fuzzy_2_tyrelife_cumulative_degradation',
       'remainder__fuzzy_3_tyrelife_cumulative_degradation',
       'remainder__fuzzy_4_tyrelife_cumulative_degradation',
       'remainder__fuzzy_0_position_position_change',
       'remainder__fuzzy_1_position_position_change',
       'remainder__fuzzy_2_position_position_change',
       'remainder__fuzzy_3_position_position_change',
       'remainder__fuzzy_0_raceprogress_lapnumber',
       'remainder__fuzzy_1_raceprogress_lapnumber',
       'remainder__fuzzy_2_raceprogress_lapnumber', 'remainder__lap_time_inv',
       'remainder__position_norm', 'remainder__is_pit_lap',
       'remainder__race_progress_sin'],
      dtype='str')

In [8]:
X_test.columns

Index(['ordinal_encoder__compound', 'target_encoder__driver',
       'target_encoder__compound', 'target_encoder__race',
       'standard_scaler__lapnumber', 'standard_scaler__position',
       'standard_scaler__raceprogress', 'standard_scaler__year',
       'robust_scaler__position_change',
       'robust_scaler__cumulative_degradation', 'robust_scaler__laptime_delta',
       'robust_scaler__laptime_s', 'robust_scaler__stint',
       'robust_scaler__driver_mean_lap', 'robust_scaler__tyrelife',
       'robust_scaler__delta_x_tyre_life', 'robust_scaler__compound_tyre_life',
       'robust_scaler__stint_progress', 'robust_scaler__tyre_life_ratio',
       'robust_scaler__degradation_per_lap',
       'robust_scaler__position_change_cum', 'robust_scaler__laps_since_pit',
       'remainder__pitstop', 'remainder__lapnumber_low',
       'remainder__lapnumber_medium', 'remainder__lapnumber_high',
       'remainder__stint_low', 'remainder__stint_medium',
       'remainder__stint_high', 'remainder__position_low',
       'remainder__position_medium', 'remainder__position_high',
       'remainder__laptime_s_low', 'remainder__laptime_s_medium',
       'remainder__laptime_s_high', 'remainder__raceprogress_low',
       'remainder__raceprogress_medium', 'remainder__raceprogress_high',
       'remainder__fuzzy_0_laptime_s_laptime_delta',
       'remainder__fuzzy_1_laptime_s_laptime_delta',
       'remainder__fuzzy_2_laptime_s_laptime_delta',
       'remainder__fuzzy_3_laptime_s_laptime_delta',
       'remainder__fuzzy_4_laptime_s_laptime_delta',
       'remainder__fuzzy_5_laptime_s_laptime_delta',
       'remainder__fuzzy_0_tyrelife_cumulative_degradation',
       'remainder__fuzzy_1_tyrelife_cumulative_degradation',
       'remainder__fuzzy_2_tyrelife_cumulative_degradation',
       'remainder__fuzzy_3_tyrelife_cumulative_degradation',
       'remainder__fuzzy_4_tyrelife_cumulative_degradation',
       'remainder__fuzzy_0_position_position_change',
       'remainder__fuzzy_1_position_position_change',
       'remainder__fuzzy_2_position_position_change',
       'remainder__fuzzy_3_position_position_change',
       'remainder__fuzzy_0_raceprogress_lapnumber',
       'remainder__fuzzy_1_raceprogress_lapnumber',
       'remainder__fuzzy_2_raceprogress_lapnumber', 'remainder__lap_time_inv',
       'remainder__position_norm', 'remainder__is_pit_lap',
       'remainder__race_progress_sin'],
      dtype='str')

## Data Dimension

In [9]:
X_train.shape

(439140, 60)

In [10]:
X_test.shape

(188165, 60)

## Check NA

In [11]:
X_train.isna().mean()

ordinal_encoder__compound                             0.0
target_encoder__driver                                0.0
target_encoder__compound                              0.0
target_encoder__race                                  0.0
standard_scaler__lapnumber                            0.0
standard_scaler__position                             0.0
standard_scaler__raceprogress                         0.0
standard_scaler__year                                 0.0
robust_scaler__position_change                        0.0
robust_scaler__cumulative_degradation                 0.0
robust_scaler__laptime_delta                          0.0
robust_scaler__laptime_s                              0.0
robust_scaler__stint                                  0.0
robust_scaler__driver_mean_lap                        0.0
robust_scaler__tyrelife                               0.0
robust_scaler__delta_x_tyre_life                      0.0
robust_scaler__compound_tyre_life                     0.0
robust_scaler__stint_progress                         0.0
robust_scaler__tyre_life_ratio                        0.0
robust_scaler__degradation_per_lap                    0.0
robust_scaler__position_change_cum                    0.0
robust_scaler__laps_since_pit                         0.0
remainder__pitstop                                    0.0
remainder__lapnumber_low                              0.0
remainder__lapnumber_medium                           0.0
remainder__lapnumber_high                             0.0
remainder__stint_low                                  0.0
remainder__stint_medium                               0.0
remainder__stint_high                                 0.0
remainder__position_low                               0.0
remainder__position_medium                            0.0
remainder__position_high                              0.0
remainder__laptime_s_low                              0.0
remainder__laptime_s_medium                           0.0
remainder__laptime_s_high                             0.0
remainder__raceprogress_low                           0.0
remainder__raceprogress_medium                        0.0
remainder__raceprogress_high                          0.0
remainder__fuzzy_0_laptime_s_laptime_delta            0.0
remainder__fuzzy_1_laptime_s_laptime_delta            0.0
remainder__fuzzy_2_laptime_s_laptime_delta            0.0
remainder__fuzzy_3_laptime_s_laptime_delta            0.0
remainder__fuzzy_4_laptime_s_laptime_delta            0.0
remainder__fuzzy_5_laptime_s_laptime_delta            0.0
remainder__fuzzy_0_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_1_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_2_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_3_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_4_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_0_position_position_change           0.0
remainder__fuzzy_1_position_position_change           0.0
remainder__fuzzy_2_position_position_change           0.0
remainder__fuzzy_3_position_position_change           0.0
remainder__fuzzy_0_raceprogress_lapnumber             0.0
remainder__fuzzy_1_raceprogress_lapnumber             0.0
remainder__fuzzy_2_raceprogress_lapnumber             0.0
remainder__lap_time_inv                               0.0
remainder__position_norm                              0.0
remainder__is_pit_lap                                 0.0
remainder__race_progress_sin                          0.0
dtype: float64

In [12]:
X_test.isna().mean()

ordinal_encoder__compound                             0.0
target_encoder__driver                                0.0
target_encoder__compound                              0.0
target_encoder__race                                  0.0
standard_scaler__lapnumber                            0.0
standard_scaler__position                             0.0
standard_scaler__raceprogress                         0.0
standard_scaler__year                                 0.0
robust_scaler__position_change                        0.0
robust_scaler__cumulative_degradation                 0.0
robust_scaler__laptime_delta                          0.0
robust_scaler__laptime_s                              0.0
robust_scaler__stint                                  0.0
robust_scaler__driver_mean_lap                        0.0
robust_scaler__tyrelife                               0.0
robust_scaler__delta_x_tyre_life                      0.0
robust_scaler__compound_tyre_life                     0.0
robust_scaler__stint_progress                         0.0
robust_scaler__tyre_life_ratio                        0.0
robust_scaler__degradation_per_lap                    0.0
robust_scaler__position_change_cum                    0.0
robust_scaler__laps_since_pit                         0.0
remainder__pitstop                                    0.0
remainder__lapnumber_low                              0.0
remainder__lapnumber_medium                           0.0
remainder__lapnumber_high                             0.0
remainder__stint_low                                  0.0
remainder__stint_medium                               0.0
remainder__stint_high                                 0.0
remainder__position_low                               0.0
remainder__position_medium                            0.0
remainder__position_high                              0.0
remainder__laptime_s_low                              0.0
remainder__laptime_s_medium                           0.0
remainder__laptime_s_high                             0.0
remainder__raceprogress_low                           0.0
remainder__raceprogress_medium                        0.0
remainder__raceprogress_high                          0.0
remainder__fuzzy_0_laptime_s_laptime_delta            0.0
remainder__fuzzy_1_laptime_s_laptime_delta            0.0
remainder__fuzzy_2_laptime_s_laptime_delta            0.0
remainder__fuzzy_3_laptime_s_laptime_delta            0.0
remainder__fuzzy_4_laptime_s_laptime_delta            0.0
remainder__fuzzy_5_laptime_s_laptime_delta            0.0
remainder__fuzzy_0_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_1_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_2_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_3_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_4_tyrelife_cumulative_degradation    0.0
remainder__fuzzy_0_position_position_change           0.0
remainder__fuzzy_1_position_position_change           0.0
remainder__fuzzy_2_position_position_change           0.0
remainder__fuzzy_3_position_position_change           0.0
remainder__fuzzy_0_raceprogress_lapnumber             0.0
remainder__fuzzy_1_raceprogress_lapnumber             0.0
remainder__fuzzy_2_raceprogress_lapnumber             0.0
remainder__lap_time_inv                               0.0
remainder__position_norm                              0.0
remainder__is_pit_lap                                 0.0
remainder__race_progress_sin                          0.0
dtype: float64

# Machine Learning

## Base

In [13]:
cv_results = cross_val_score(
    estimator=XGBClassifier(random_state=42, verbosity=0), 
    X=X_train, 
    y=y_train.PitNextLap, 
    scoring='roc_auc', 
    cv=StratifiedKFold(random_state=42, shuffle=True), 
    n_jobs=-1
)

In [14]:
cv_results.mean()

np.float64(0.9452400416659223)

In [15]:
model = XGBClassifier(random_state=42, verbosity=0).fit(X_train, y_train.PitNextLap)

## Feature Selection

In [26]:
perm_result = permutation_importance(
    estimator=model, 
    X=X_train, 
    y=y_train.PitNextLap, 
    n_jobs=-1, 
    scoring='roc_auc'
)


importance_df = pd.DataFrame({
    "feature": X_train.columns.tolist(),
    "importance_mean": perm_result.importances_mean,
    "importance_std": perm_result.importances_std
}).sort_values(by="importance_mean", ascending=False)

In [27]:
importance_df

,feature,importance_mean,importance_std
12,robust_scaler__stint,0.082732,0.000323
7,standard_scaler__year,0.066972,0.000439
18,robust_scaler__tyre_life_ratio,0.025760,0.000117
14,robust_scaler__tyrelife,0.023285,0.000123
3,target_encoder__race,0.011125,0.000047
10,robust_scaler__laptime_delta,0.007145,0.000064
15,robust_scaler__delta_x_tyre_life,0.004168,0.000069
8,robust_scaler__position_change,0.003230,0.000034
9,robust_scaler__cumulative_degradation,0.003154,0.000063
36,remainder__raceprogress_medium,0.002551,0.000022
19,robust_scaler__degradation_per_lap,0.002512,0.000027
0,ordinal_encoder__compound,0.002251,0.000032
22,remainder__pitstop,0.002168,0.000042
37,remainder__raceprogress_high,0.001997,0.000049
2,target_encoder__compound,0.001944,0.000037
5,standard_scaler__position,0.001804,0.000017
4,standard_scaler__lapnumber,0.001743,0.000031
32,remainder__laptime_s_low,0.001542,0.000023
13,robust_scaler__driver_mean_lap,0.001428,0.000032
59,remainder__race_progress_sin,0.001375,0.000035
33,remainder__laptime_s_medium,0.001369,0.000023
40,remainder__fuzzy_2_laptime_s_laptime_delta,0.001270,0.000014
41,remainder__fuzzy_3_laptime_s_laptime_delta,0.001228,0.000012
38,remainder__fuzzy_0_laptime_s_laptime_delta,0.001218,0.000042
1,target_encoder__driver,0.001194,0.000014
27,remainder__stint_medium,0.001146,0.000017
24,remainder__lapnumber_medium,0.001063,0.000048
43,remainder__fuzzy_5_laptime_s_laptime_delta,0.000964,0.000023
47,remainder__fuzzy_3_tyrelife_cumulative_degrada...,0.000958,0.000024
49,remainder__fuzzy_0_position_position_change,0.000865,0.000008
17,robust_scaler__stint_progress,0.000851,0.000012
6,standard_scaler__raceprogress,0.000833,0.000018
44,remainder__fuzzy_0_tyrelife_cumulative_degrada...,0.000795,0.000019
45,remainder__fuzzy_1_tyrelife_cumulative_degrada...,0.000765,0.000019
34,remainder__laptime_s_high,0.000764,0.000027
39,remainder__fuzzy_1_laptime_s_laptime_delta,0.000752,0.000017
52,remainder__fuzzy_3_position_position_change,0.000731,0.000020
48,remainder__fuzzy_4_tyrelife_cumulative_degrada...,0.000722,0.000031
42,remainder__fuzzy_4_laptime_s_laptime_delta,0.000710,0.000012
16,robust_scaler__compound_tyre_life,0.000705,0.000009
35,remainder__raceprogress_low,0.000656,0.000025
50,remainder__fuzzy_1_position_position_change,0.000654,0.000010
20,robust_scaler__position_change_cum,0.000596,0.000013
54,remainder__fuzzy_1_raceprogress_lapnumber,0.000592,0.000011
46,remainder__fuzzy_2_tyrelife_cumulative_degrada...,0.000582,0.000015
53,remainder__fuzzy_0_raceprogress_lapnumber,0.000572,0.000013
51,remainder__fuzzy_2_position_position_change,0.000551,0.000014
11,robust_scaler__laptime_s,0.000473,0.000015
55,remainder__fuzzy_2_raceprogress_lapnumber,0.000469,0.000009
30,remainder__position_medium,0.000461,0.000012
56,remainder__lap_time_inv,0.000390,0.000017
21,robust_scaler__laps_since_pit,0.000245,0.000004
26,remainder__stint_low,0.000000,0.000000
25,remainder__lapnumber_high,0.000000,0.000000
23,remainder__lapnumber_low,0.000000,0.000000
29,remainder__position_low,0.000000,0.000000
28,remainder__stint_high,0.000000,0.000000
31,remainder__position_high,0.000000,0.000000
57,remainder__position_norm,0.000000,0.000000
58,remainder__is_pit_lap,0.000000,0.000000

In [18]:
importance_df.query("importance_mean <= 0").feature.tolist()

['remainder__stint_low',
 'remainder__lapnumber_high',
 'remainder__lapnumber_low',
 'remainder__position_low',
 'remainder__stint_high',
 'remainder__position_high',
 'remainder__position_norm',
 'remainder__is_pit_lap']

In [22]:
drop_feat = DropFeatures(features_to_drop=importance_df.query("importance_mean <= 0").feature.tolist())

## Fine Tuning

In [23]:
def objective(trial, X, y):

    scale_pos_weight = (y.PitNextLap == 0).sum() / (y.PitNextLap == 1).sum()
    
    params = {
        "objective": "binary:logistic",
        "eval_metric": "auc",
        "verbosity": 0,
        "scale_pos_weight": scale_pos_weight,
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
        "n_estimators": trial.suggest_int("n_estimators", 100, 1500),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10, log=True),
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    aucs = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]
        
        model = Pipeline([('drop_feat', drop_feat), ('xgb', XGBClassifier(**params))])
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]
        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)


study = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=50, n_jobs=-1, show_progress_bar=True)

[I 2026-05-05 14:16:55,046] A new study created in memory with name: no-name-67a65bf9-df40-4c05-a9e3-e9333bf68800

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-05 14:18:11,364] Trial 8 finished with value: 0.9323216108047673 and parameters: {'max_depth': 4, 'learning_rate': 0.032490127141286615, 'n_estimators': 124, 'subsample': 0.7518158280578091, 'colsample_bytree': 0.8777085073261768, 'gamma': 4.8285610052348416, 'reg_alpha': 0.027942409699874375, 'reg_lambda': 4.2012410421555716e-08}. Best is trial 8 with value: 0.9323216108047673.
[I 2026-05-05 14:20:54,172] Trial 4 finished with value: 0.9346356765216512 and parameters: {'max_depth': 8, 'learning_rate': 0.0010677570335650578, 'n_estimators': 205, 'subsample': 0.8491472396768136, 'colsample_bytree': 0.5409403469710052, 'gamma': 0.6761497156933138, 'reg_alpha': 9.865973324902028e-06, 'reg_lambda': 0.2874479211800762}. Best is trial 4 with value: 0.9346356765216512.
[I 2026-05-05 14:23:52,842] Trial 1 finished with value: 0.9347044163554827 and parameters: {'max_depth': 4, 'learning_rate': 0.006723999390717626, 'n_estimators': 815, 'subsample': 0.8518440170494503, 'colsample_bytree': 0.5431611593060519, 'gamma': 4.4407048247500045, 'reg_alpha': 0.9536118476134743, 'reg_lambda': 0.0008987333622694267}. Best is trial 1 with value: 0.9347044163554827.
[I 2026-05-05 14:24:54,401] Trial 11 finished with value: 0.9456017739068695 and parameters: {'max_depth': 9, 'learning_rate': 0.014505692881504077, 'n_estimators': 338, 'subsample': 0.7204095365882772, 'colsample_bytree': 0.7736964325428808, 'gamma': 1.7757189330341454, 'reg_alpha': 0.001292897372310571, 'reg_lambda': 1.2359216345299197e-05}. Best is trial 11 with value: 0.9456017739068695.
[I 2026-05-05 14:25:26,978] Trial 3 finished with value: 0.9434616499164253 and parameters: {'max_depth': 4, 'learning_rate': 0.03419251067206758, 'n_estimators': 1330, 'subsample': 0.9836694930666933, 'colsample_bytree': 0.5527333951536222, 'gamma': 4.482399926038516, 'reg_alpha': 1.5006885454344376e-05, 'reg_lambda': 0.32501222667238083}. Best is trial 11 with value: 0.9456017739068695.
[I 2026-05-05 14:25:36,153] Trial 2 pruned.
[I 2026-05-05 14:25:57,972] Trial 14 pruned.
[I 2026-05-05 14:26:43,636] Trial 12 finished with value: 0.9382129345078318 and parameters: {'max_depth': 7, 'learning_rate': 0.0037647547712299665, 'n_estimators': 529, 'subsample': 0.7825945590068499, 'colsample_bytree': 0.7933407243069002, 'gamma': 2.9293003063041736, 'reg_alpha': 3.0266817677740715e-07, 'reg_lambda': 8.129163544475568e-08}. Best is trial 11 with value: 0.9456017739068695.
[I 2026-05-05 14:26:57,215] Trial 9 finished with value: 0.9439008512453757 and parameters: {'max_depth': 9, 'learning_rate': 0.07789780968824359, 'n_estimators': 544, 'subsample': 0.51676102436596, 'colsample_bytree': 0.9517554692482921, 'gamma': 3.0355504668243767, 'reg_alpha': 7.1962711741013465e-06, 'reg_lambda': 3.423293181306828e-07}. Best is trial 11 with value: 0.9456017739068695.
[I 2026-05-05 14:27:33,059] Trial 10 pruned.
[I 2026-05-05 14:27:42,988] Trial 7 pruned.
[I 2026-05-05 14:28:12,810] Trial 13 finished with value: 0.9467773845685447 and parameters: {'max_depth': 7, 'learning_rate': 0.08111984333457946, 'n_estimators': 1391, 'subsample': 0.9584633050678766, 'colsample_bytree': 0.7903055599168092, 'gamma': 4.0036634367555965, 'reg_alpha': 2.357865396565015e-08, 'reg_lambda': 0.08474823367171727}. Best is trial 13 with value: 0.9467773845685447.
[I 2026-05-05 14:28:39,108] Trial 5 finished with value: 0.9425030591361715 and parameters: {'max_depth': 9, 'learning_rate': 0.0045784152885949845, 'n_estimators': 486, 'subsample': 0.8980218904831976, 'colsample_bytree': 0.7442765587153524, 'gamma': 2.822891721828817, 'reg_alpha': 0.04149591199839066, 'reg_lambda': 4.011489015285798}. Best is trial 13 with value: 0.9467773845685447.
[I 2026-05-05 14:30:00,644] Trial 15 pruned.
[I 2026-05-05 14:30:33,844] Trial 6 pruned.
[I 2026-05-05 14:31:22,961] Trial 18 pruned.
[I 2026-05-05 14:32:00,440] Trial 20 pruned.
[I 2026-05-05 14:36:58,464] Trial 22 pruned.
[I 2026-05-05 14:38:21,534] Trial 0 finished with value: 0.9464292125000465 and parameters: {'max_depth': 8, 'learning_rate': 0.04234156253750265, 'n_estimators': 1405, 'subsample': 0.7419980877439732, 'colsample_bytree': 0.9253887571058766, 'gamma': 1.4184337033080918, 'reg_alpha': 0.000875121494867981, 'reg_lambda': 0.00013211761606352708}. Best is trial 13 with value: 0.9467773845685447.
[I 2026-05-05 14:40:59,280] Trial 28 finished with value: 0.9462068536503345 and parameters: {'max_depth': 10, 'learning_rate': 0.08493753938517963, 'n_estimators': 978, 'subsample': 0.9937417267989128, 'colsample_bytree': 0.670394004622046, 'gamma': 1.4593456909399731, 'reg_alpha': 0.0011412262839000837, 'reg_lambda': 0.015442678188125154}. Best is trial 13 with value: 0.9467773845685447.
[I 2026-05-05 14:40:59,671] Trial 19 finished with value: 0.9473138757794587 and parameters: {'max_depth': 8, 'learning_rate': 0.04299485992463524, 'n_estimators': 1456, 'subsample': 0.8939304925996443, 'colsample_bytree': 0.9379109335697863, 'gamma': 3.5390657747991474, 'reg_alpha': 0.004094312554089439, 'reg_lambda': 1.0282452805187835e-07}. Best is trial 19 with value: 0.9473138757794587.
[I 2026-05-05 14:48:13,134] Trial 21 finished with value: 0.9475823587446099 and parameters: {'max_depth': 10, 'learning_rate': 0.016176864701808936, 'n_estimators': 816, 'subsample': 0.611856724552163, 'colsample_bytree': 0.6736545449510802, 'gamma': 1.7095061696344027, 'reg_alpha': 0.0014987909618912746, 'reg_lambda': 2.5165228686957294e-05}. Best is trial 21 with value: 0.9475823587446099.
[I 2026-05-05 14:49:17,400] Trial 30 finished with value: 0.9471127682026264 and parameters: {'max_depth': 7, 'learning_rate': 0.04902791835276055, 'n_estimators': 1148, 'subsample': 0.9959180936076522, 'colsample_bytree': 0.6737951654974567, 'gamma': 1.3668698272384778, 'reg_alpha': 0.0030686968556374876, 'reg_lambda': 0.010555146649462409}. Best is trial 21 with value: 0.9475823587446099.
[I 2026-05-05 14:52:02,318] Trial 32 finished with value: 0.9471271140556154 and parameters: {'max_depth': 7, 'learning_rate': 0.04042369880625255, 'n_estimators': 1104, 'subsample': 0.9239332652453017, 'colsample_bytree': 0.9180213680637728, 'gamma': 3.7153244838489066, 'reg_alpha': 0.004236976567604704, 'reg_lambda': 0.015339028696286042}. Best is trial 21 with value: 0.9475823587446099.
[I 2026-05-05 14:52:27,689] Trial 23 finished with value: 0.9484218890386267 and parameters: {'max_depth': 10, 'learning_rate': 0.019041022033151486, 'n_estimators': 1064, 'subsample': 0.9771051014520294, 'colsample_bytree': 0.6790162492502597, 'gamma': 1.5603579187039802, 'reg_alpha': 1.0017375276883564e-08, 'reg_lambda': 5.614155244387563}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 14:52:52,350] Trial 27 finished with value: 0.9478394535318694 and parameters: {'max_depth': 10, 'learning_rate': 0.016745195541529843, 'n_estimators': 867, 'subsample': 0.9685697738003856, 'colsample_bytree': 0.6620078117267482, 'gamma': 1.6329448994502698, 'reg_alpha': 1.825475748027792e-08, 'reg_lambda': 0.007869845565631466}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 14:53:06,558] Trial 29 finished with value: 0.9473694512925471 and parameters: {'max_depth': 8, 'learning_rate': 0.01741630963606043, 'n_estimators': 1013, 'subsample': 0.9844818816526291, 'colsample_bytree': 0.6751718088201467, 'gamma': 1.725738565665356, 'reg_alpha': 0.0013217430936004564, 'reg_lambda': 0.012996814331458509}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 14:53:06,908] Trial 26 finished with value: 0.9475822479950274 and parameters: {'max_depth': 10, 'learning_rate': 0.01583836125755207, 'n_estimators': 1006, 'subsample': 0.9994925950119636, 'colsample_bytree': 0.6873978778263485, 'gamma': 1.7334384656305024, 'reg_alpha': 1.3113304821969203e-08, 'reg_lambda': 3.895615377216269e-05}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 14:53:41,165] Trial 17 finished with value: 0.947651457061685 and parameters: {'max_depth': 9, 'learning_rate': 0.019564449797169595, 'n_estimators': 1491, 'subsample': 0.933706979422706, 'colsample_bytree': 0.8763747820709891, 'gamma': 0.969063531856843, 'reg_alpha': 6.183996705506459e-06, 'reg_lambda': 4.1510972057168605e-07}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 14:54:18,238] Trial 25 finished with value: 0.9478626082079545 and parameters: {'max_depth': 10, 'learning_rate': 0.01701288420951076, 'n_estimators': 1102, 'subsample': 0.9905420898850537, 'colsample_bytree': 0.6406379404180957, 'gamma': 1.655936984719954, 'reg_alpha': 2.277736711260794e-08, 'reg_lambda': 2.4899530548243305e-05}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 14:54:27,942] Trial 24 finished with value: 0.9478247359330636 and parameters: {'max_depth': 10, 'learning_rate': 0.017977453505701894, 'n_estimators': 1116, 'subsample': 0.9653121735304161, 'colsample_bytree': 0.6980185299732518, 'gamma': 1.377453481705769, 'reg_alpha': 4.321901870198522e-08, 'reg_lambda': 7.198247919851635e-05}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 14:57:03,204] Trial 16 finished with value: 0.946066126460335 and parameters: {'max_depth': 10, 'learning_rate': 0.005136224949121999, 'n_estimators': 963, 'subsample': 0.831932426912672, 'colsample_bytree': 0.981377705855268, 'gamma': 4.054074982601877, 'reg_alpha': 1.576924655375483e-05, 'reg_lambda': 4.836392200461546e-06}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 14:57:21,006] Trial 33 finished with value: 0.9471861087730392 and parameters: {'max_depth': 7, 'learning_rate': 0.050328757212536795, 'n_estimators': 1152, 'subsample': 0.9340199588753595, 'colsample_bytree': 0.6561848007959312, 'gamma': 3.8020314213795303, 'reg_alpha': 0.007169945807182464, 'reg_lambda': 0.015454808887048494}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 15:01:37,016] Trial 31 finished with value: 0.9474707362586076 and parameters: {'max_depth': 8, 'learning_rate': 0.04875151324963009, 'n_estimators': 1166, 'subsample': 0.5883606676226631, 'colsample_bytree': 0.6788426508971406, 'gamma': 1.08786577572663, 'reg_alpha': 9.449977371413672, 'reg_lambda': 0.01567297450701224}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 15:06:17,836] Trial 35 finished with value: 0.9478887528763714 and parameters: {'max_depth': 8, 'learning_rate': 0.02465891771294022, 'n_estimators': 942, 'subsample': 0.9279582395435795, 'colsample_bytree': 0.6331515909425675, 'gamma': 2.3656505787565667, 'reg_alpha': 0.010125557901343752, 'reg_lambda': 0.004054220319702933}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 15:07:27,219] Trial 40 finished with value: 0.9483209134666023 and parameters: {'max_depth': 9, 'learning_rate': 0.026228307535305168, 'n_estimators': 701, 'subsample': 0.9372750568613191, 'colsample_bytree': 0.6354665362158618, 'gamma': 0.8929201289393816, 'reg_alpha': 9.730025432828064e-08, 'reg_lambda': 6.767983740490229}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 15:07:33,383] Trial 34 finished with value: 0.9474629336004284 and parameters: {'max_depth': 8, 'learning_rate': 0.018149212008430775, 'n_estimators': 1119, 'subsample': 0.5907768505091392, 'colsample_bytree': 0.672415009438887, 'gamma': 0.9428682602674775, 'reg_alpha': 0.006728811521020004, 'reg_lambda': 0.006316727786064064}. Best is trial 23 with value: 0.9484218890386267.
[I 2026-05-05 15:11:29,762] Trial 41 finished with value: 0.9484421816411709 and parameters: {'max_depth': 9, 'learning_rate': 0.0233491127311993, 'n_estimators': 914, 'subsample': 0.9394730584427258, 'colsample_bytree': 0.6087826506671938, 'gamma': 2.2732064393322244, 'reg_alpha': 1.2392672557627898e-07, 'reg_lambda': 5.8556445358490805}. Best is trial 41 with value: 0.9484421816411709.
[I 2026-05-05 15:12:53,401] Trial 39 finished with value: 0.9483320929982615 and parameters: {'max_depth': 10, 'learning_rate': 0.024453981346811617, 'n_estimators': 827, 'subsample': 0.5871246919718858, 'colsample_bytree': 0.6123802392276664, 'gamma': 2.3749569364891183, 'reg_alpha': 1.1650050749252056e-07, 'reg_lambda': 6.939147180015145}. Best is trial 41 with value: 0.9484421816411709.
[I 2026-05-05 15:13:50,403] Trial 36 finished with value: 0.9473854650958223 and parameters: {'max_depth': 10, 'learning_rate': 0.02366059228214969, 'n_estimators': 908, 'subsample': 0.5591699150955727, 'colsample_bytree': 0.6368363583581592, 'gamma': 2.1090593965746445, 'reg_alpha': 0.18520808237152178, 'reg_lambda': 1.0458030737289755e-08}. Best is trial 41 with value: 0.9484421816411709.
[I 2026-05-05 15:13:55,180] Trial 37 finished with value: 0.9482447968515132 and parameters: {'max_depth': 10, 'learning_rate': 0.022028017399920292, 'n_estimators': 851, 'subsample': 0.6129098726758313, 'colsample_bytree': 0.6178294859396657, 'gamma': 0.8927360618106936, 'reg_alpha': 1.5426685092447754e-07, 'reg_lambda': 4.370349506846158}. Best is trial 41 with value: 0.9484421816411709.
[I 2026-05-05 15:13:57,124] Trial 38 finished with value: 0.9482699954726366 and parameters: {'max_depth': 10, 'learning_rate': 0.023763952308168298, 'n_estimators': 871, 'subsample': 0.5709157346618182, 'colsample_bytree': 0.6210272843814993, 'gamma': 2.116777836838917, 'reg_alpha': 1.6902181876366703e-07, 'reg_lambda': 5.96364517334897}. Best is trial 41 with value: 0.9484421816411709.
[I 2026-05-05 15:15:14,435] Trial 42 finished with value: 0.9486323646956348 and parameters: {'max_depth': 10, 'learning_rate': 0.02351208051350585, 'n_estimators': 910, 'subsample': 0.923001011398858, 'colsample_bytree': 0.6037844092494867, 'gamma': 1.062979397487378, 'reg_alpha': 1.125234552339411e-07, 'reg_lambda': 7.392547277054004}. Best is trial 42 with value: 0.9486323646956348.
[I 2026-05-05 15:15:53,310] Trial 44 finished with value: 0.9473013139130074 and parameters: {'max_depth': 9, 'learning_rate': 0.009536108360897846, 'n_estimators': 870, 'subsample': 0.952183829861887, 'colsample_bytree': 0.6227393846159386, 'gamma': 2.251557443133354, 'reg_alpha': 7.991561794501372e-08, 'reg_lambda': 0.0005262824664906665}. Best is trial 42 with value: 0.9486323646956348.
[I 2026-05-05 15:18:05,215] Trial 45 finished with value: 0.9472264013327318 and parameters: {'max_depth': 9, 'learning_rate': 0.009274988749981755, 'n_estimators': 866, 'subsample': 0.9579015477692872, 'colsample_bytree': 0.6000593511758513, 'gamma': 2.2158094743547587, 'reg_alpha': 1.403515396277572e-07, 'reg_lambda': 0.00046485845913279966}. Best is trial 42 with value: 0.9486323646956348.
[I 2026-05-05 15:18:37,405] Trial 43 finished with value: 0.9480443832550656 and parameters: {'max_depth': 9, 'learning_rate': 0.009828267945985326, 'n_estimators': 1192, 'subsample': 0.9443606372685454, 'colsample_bytree': 0.6128751559163172, 'gamma': 2.221063791795989, 'reg_alpha': 1.3143341557491181e-07, 'reg_lambda': 7.597504710357288}. Best is trial 42 with value: 0.9486323646956348.
[I 2026-05-05 15:18:59,330] Trial 47 finished with value: 0.9467803477133903 and parameters: {'max_depth': 9, 'learning_rate': 0.00939843664833237, 'n_estimators': 695, 'subsample': 0.8205225187471412, 'colsample_bytree': 0.6073550187786727, 'gamma': 2.236243784956121, 'reg_alpha': 1.0682085919449279e-07, 'reg_lambda': 8.301730167744264}. Best is trial 42 with value: 0.9486323646956348.
[I 2026-05-05 15:19:15,685] Trial 48 finished with value: 0.9468511436685564 and parameters: {'max_depth': 9, 'learning_rate': 0.009023805036440536, 'n_estimators': 736, 'subsample': 0.8108203427952372, 'colsample_bytree': 0.6247122192500524, 'gamma': 2.109962132999881, 'reg_alpha': 1.8644670414693066e-07, 'reg_lambda': 7.744272055810035}. Best is trial 42 with value: 0.9486323646956348.
[I 2026-05-05 15:19:22,890] Trial 46 finished with value: 0.9473673624957094 and parameters: {'max_depth': 9, 'learning_rate': 0.010340929025215278, 'n_estimators': 850, 'subsample': 0.8151805016522291, 'colsample_bytree': 0.6069209227279951, 'gamma': 2.2697759375444972, 'reg_alpha': 1.1777314654864674e-07, 'reg_lambda': 0.002259352672665893}. Best is trial 42 with value: 0.9486323646956348.
[I 2026-05-05 15:19:28,037] Trial 49 finished with value: 0.9483268854045857 and parameters: {'max_depth': 9, 'learning_rate': 0.026135995099660844, 'n_estimators': 713, 'subsample': 0.8117783732247142, 'colsample_bytree': 0.6050258961295499, 'gamma': 2.263907154530961, 'reg_alpha': 1.434459600315361e-07, 'reg_lambda': 5.716258489901317}. Best is trial 42 with value: 0.9486323646956348.

In [24]:
scale_pos_weight = (y_train.PitNextLap == 0).sum() / (y_train.PitNextLap == 1).sum()

model_tuned = XGBClassifier(
    objective="binary:logistic",
    eval_metric="auc",
    verbosity=0,
    scale_pos_weight=scale_pos_weight,
    **study.best_params
)

pipe_tuned = Pipeline([('drop_feat', drop_feat), ('xgb', model_tuned)])
pipe_tuned.fit(X_train, y_train.PitNextLap)

Pipeline(steps=[('drop_feat',
                 DropFeatures(features_to_drop=['remainder__stint_low',
                                                'remainder__lapnumber_high',
                                                'remainder__lapnumber_low',
                                                'remainder__position_low',
                                                'remainder__stint_high',
                                                'remainder__position_high',
                                                'remainder__position_norm',
                                                'remainder__is_pit_lap'])),
                ('xgb',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_byleve...
                               gamma=1.062979397487378, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None,
                               learning_rate=0.02351208051350585, max_bin=None,
                               max_cat_threshold=None, max_cat_to_onehot=None,
                               max_delta_step=None, max_depth=10,
                               max_leaves=None, min_child_weight=None,
                               missing=nan, monotone_constraints=None,
                               multi_strategy=None, n_estimators=910,
                               n_jobs=None, num_parallel_tree=None, ...))])

# Deploy

In [25]:
dump_pickle(pipe_tuned, '../models/model_xgboost.pkl')