# Imports

In [15]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.metrics import roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.inspection import permutation_importance
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split

from feature_engine.selection import DropFeatures

## Utils

In [2]:
def dump_pickle(file_obj, file_path):
    with open(file_path, 'bw') as file:
        pickle.dump(file_obj, file)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/X_train.parquet')
X_test = pd.read_parquet('../data/X_test.parquet')

y_train = pd.read_parquet('../data/y_train.parquet')

In [4]:
X_train.head()

,ordinal_encoder__compound,target_encoder__driver,target_encoder__compound,target_encoder__race,standard_scaler__lapnumber,standard_scaler__position,standard_scaler__raceprogress,standard_scaler__year,robust_scaler__position_change,robust_scaler__cumulative_degradation,...,remainder__fuzzy_1_position_position_change,remainder__fuzzy_2_position_position_change,remainder__fuzzy_3_position_position_change,remainder__fuzzy_0_raceprogress_lapnumber,remainder__fuzzy_1_raceprogress_lapnumber,remainder__fuzzy_2_raceprogress_lapnumber,remainder__lap_time_inv,remainder__position_norm,remainder__is_pit_lap,remainder__race_progress_sin
id,,,,,,,,,,,,,,,,,,,,,
0,0.50,0.203815,0.328482,0.154734,1.585901,-0.308849,1.487008,-1.486487,1.666667,1.040769,...,0.947453,0.005655,0.020178,0.000549,0.997580,0.001872,0.012740,0.40,0,0.781831
1,0.50,0.199575,0.327181,0.176114,0.229628,-1.066602,0.033534,1.440545,-1.000000,-5.009333,...,0.074107,0.081854,0.098684,0.015175,0.007697,0.977128,0.013316,0.20,1,0.885456
2,0.50,0.218840,0.326837,0.187526,2.116616,0.638343,1.902200,-1.486487,1.000000,-1.970285,...,0.226475,0.059038,0.614716,0.024077,0.912645,0.063278,0.014095,0.65,0,0.537300
3,0.25,0.200526,0.100888,0.145166,-1.244581,-0.498287,-1.029455,-0.510810,0.000000,0.338641,...,0.088099,0.041344,0.113803,0.950726,0.010153,0.039121,0.010598,0.35,0,0.239316
4,0.50,0.192082,0.327657,0.214557,0.170660,-1.445478,0.092589,-1.486487,1.000000,0.169816,...,0.256086,0.040890,0.083385,0.009589,0.004844,0.985566,0.009270,0.10,1,0.906308

In [5]:
X_test.head()

,ordinal_encoder__compound,target_encoder__driver,target_encoder__compound,target_encoder__race,standard_scaler__lapnumber,standard_scaler__position,standard_scaler__raceprogress,standard_scaler__year,robust_scaler__position_change,robust_scaler__cumulative_degradation,...,remainder__fuzzy_1_position_position_change,remainder__fuzzy_2_position_position_change,remainder__fuzzy_3_position_position_change,remainder__fuzzy_0_raceprogress_lapnumber,remainder__fuzzy_1_raceprogress_lapnumber,remainder__fuzzy_2_raceprogress_lapnumber,remainder__lap_time_inv,remainder__position_norm,remainder__is_pit_lap,remainder__race_progress_sin
id,,,,,,,,,,,,,,,,,,,,,
439140,0.25,0.182308,0.101132,0.133462,-0.124182,-1.066602,0.261317,-0.510810,0.000000,0.396609,...,0.001144,0.000465,0.000894,0.067702,0.028176,0.904122,0.010708,0.20,0,0.954721
439141,0.25,0.356316,0.101132,0.150547,0.052723,-1.634917,0.300590,-0.510810,0.000000,0.470778,...,0.081596,0.033933,0.053686,0.019477,0.011500,0.969023,0.011005,0.05,0,0.963550
439142,0.25,0.121796,0.101132,0.133462,0.052723,0.259466,0.489100,-0.510810,0.000000,0.301036,...,0.087683,0.072629,0.701444,0.038897,0.031448,0.929655,0.010768,0.55,0,0.992709
439143,0.00,0.198847,0.193475,0.253713,-1.008708,1.017219,-1.025511,0.464868,0.333333,0.724449,...,0.023113,0.022859,0.935769,0.984826,0.002887,0.012287,0.010530,0.75,0,0.242362
439144,0.50,0.197127,0.327536,0.114051,1.703838,0.448905,1.518343,0.464868,2.333333,0.003617,...,0.718809,0.040632,0.151701,0.002043,0.991340,0.006618,0.010090,0.60,0,0.766044

# Machine Learning

## Base

In [6]:
cv_results = cross_val_score(
    estimator=HistGradientBoostingClassifier(class_weight='balanced', verbose=0), 
    X=X_train, 
    y=y_train.PitNextLap, 
    scoring='roc_auc', 
    cv=StratifiedKFold(random_state=42, shuffle=True), 
    n_jobs=-1
)

In [7]:
cv_results.mean()

np.float64(0.9429598711008129)

In [9]:
model = HistGradientBoostingClassifier(class_weight='balanced', verbose=0)
model.fit(X_train, y_train.PitNextLap)

HistGradientBoostingClassifier(class_weight='balanced')

## Feature Selection

In [10]:
perm_result = permutation_importance(
    estimator=model, 
    X=X_train, 
    y=y_train.PitNextLap, 
    n_jobs=-1, 
    scoring='roc_auc'
)


importance_df = pd.DataFrame({
    "feature": X_train.columns.tolist(),
    "importance_mean": perm_result.importances_mean,
    "importance_std": perm_result.importances_std
}).sort_values(by="importance_mean", ascending=False)

In [11]:
importance_df

,feature,importance_mean,importance_std
12,robust_scaler__stint,0.098400,4.046051e-04
7,standard_scaler__year,0.089156,6.239892e-04
18,robust_scaler__tyre_life_ratio,0.025835,1.152948e-04
14,robust_scaler__tyrelife,0.018556,1.312438e-04
3,target_encoder__race,0.009441,6.613894e-05
10,robust_scaler__laptime_delta,0.005352,5.615044e-05
15,robust_scaler__delta_x_tyre_life,0.003745,1.218361e-04
0,ordinal_encoder__compound,0.002248,3.385269e-05
8,robust_scaler__position_change,0.001971,1.753807e-05
22,remainder__pitstop,0.001925,5.760198e-05
2,target_encoder__compound,0.001856,3.851995e-05
11,robust_scaler__laptime_s,0.001319,3.794962e-05
5,standard_scaler__position,0.001146,5.754224e-06
9,robust_scaler__cumulative_degradation,0.001069,1.286439e-05
59,remainder__race_progress_sin,0.000967,2.633704e-05
6,standard_scaler__raceprogress,0.000731,2.055598e-05
27,remainder__stint_medium,0.000729,9.689632e-06
13,robust_scaler__driver_mean_lap,0.000582,5.474103e-06
40,remainder__fuzzy_2_laptime_s_laptime_delta,0.000572,2.448221e-05
19,robust_scaler__degradation_per_lap,0.000522,2.147547e-05
47,remainder__fuzzy_3_tyrelife_cumulative_degrada...,0.000501,2.194813e-05
33,remainder__laptime_s_medium,0.000498,1.295827e-05
39,remainder__fuzzy_1_laptime_s_laptime_delta,0.000417,8.555068e-06
36,remainder__raceprogress_medium,0.000405,1.620758e-05
1,target_encoder__driver,0.000329,9.126171e-06
53,remainder__fuzzy_0_raceprogress_lapnumber,0.000313,1.399464e-05
48,remainder__fuzzy_4_tyrelife_cumulative_degrada...,0.000301,1.873782e-05
52,remainder__fuzzy_3_position_position_change,0.000292,1.821556e-05
49,remainder__fuzzy_0_position_position_change,0.000288,1.785173e-05
32,remainder__laptime_s_low,0.000269,9.132528e-06
41,remainder__fuzzy_3_laptime_s_laptime_delta,0.000266,6.483276e-06
16,robust_scaler__compound_tyre_life,0.000254,5.789404e-06
45,remainder__fuzzy_1_tyrelife_cumulative_degrada...,0.000229,1.217055e-05
43,remainder__fuzzy_5_laptime_s_laptime_delta,0.000219,1.232828e-05
54,remainder__fuzzy_1_raceprogress_lapnumber,0.000199,3.910281e-06
42,remainder__fuzzy_4_laptime_s_laptime_delta,0.000199,8.264545e-06
17,robust_scaler__stint_progress,0.000191,6.745663e-06
38,remainder__fuzzy_0_laptime_s_laptime_delta,0.000186,1.043457e-05
56,remainder__lap_time_inv,0.000185,7.010030e-06
50,remainder__fuzzy_1_position_position_change,0.000174,1.140189e-05
30,remainder__position_medium,0.000140,4.778027e-06
4,standard_scaler__lapnumber,0.000093,8.112372e-06
20,robust_scaler__position_change_cum,0.000083,3.271930e-06
46,remainder__fuzzy_2_tyrelife_cumulative_degrada...,0.000064,4.012439e-06
44,remainder__fuzzy_0_tyrelife_cumulative_degrada...,0.000060,2.168412e-06
24,remainder__lapnumber_medium,0.000053,4.321704e-06
51,remainder__fuzzy_2_position_position_change,0.000044,3.765074e-06
55,remainder__fuzzy_2_raceprogress_lapnumber,0.000044,1.556312e-06
35,remainder__raceprogress_low,0.000043,5.058810e-06
29,remainder__position_low,0.000039,3.259526e-06
21,robust_scaler__laps_since_pit,0.000013,8.425438e-07
26,remainder__stint_low,0.000008,1.689068e-06
37,remainder__raceprogress_high,0.000000,0.000000e+00
25,remainder__lapnumber_high,0.000000,0.000000e+00
31,remainder__position_high,0.000000,0.000000e+00
34,remainder__laptime_s_high,0.000000,0.000000e+00
57,remainder__position_norm,0.000000,0.000000e+00
28,remainder__stint_high,0.000000,0.000000e+00
58,remainder__is_pit_lap,0.000000,0.000000e+00
23,remainder__lapnumber_low,-0.000004,7.070504e-07

In [12]:
importance_df.query("importance_mean <= 0").feature.tolist()

['remainder__raceprogress_high',
 'remainder__lapnumber_high',
 'remainder__position_high',
 'remainder__laptime_s_high',
 'remainder__position_norm',
 'remainder__stint_high',
 'remainder__is_pit_lap',
 'remainder__lapnumber_low']

In [16]:
drop_feat = DropFeatures(features_to_drop=importance_df.query("importance_mean <= 0").feature.tolist())

## Fine Tuning

In [18]:
def objective(trial, X, y):

    params = {
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 20, 100),
        "l2_regularization": trial.suggest_float("l2_regularization", 0.0, 10.0),
        "max_bins": trial.suggest_int("max_bins", 64, 255),
        "max_iter": 1000,
        "early_stopping": True,
        "validation_fraction": 0.1,
        "n_iter_no_change": 50,
        "random_state": 42
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = Pipeline([('drop_feat', drop_feat), ('hist', HistGradientBoostingClassifier(**params))])
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

study = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=50, n_jobs=-1, show_progress_bar=True)


print("Best AUC:", study.best_value)
print("Best params:", study.best_params)

[I 2026-05-05 18:43:36,045] A new study created in memory with name: no-name-42647aae-1ced-4ced-af24-74def7f7a378

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-05 18:52:39,380] Trial 1 finished with value: 0.9381805118892965 and parameters: {'learning_rate': 0.028091270865478902, 'max_depth': 3, 'min_samples_leaf': 26, 'l2_regularization': 4.543837205389343, 'max_bins': 151}. Best is trial 1 with value: 0.9381805118892965.
[I 2026-05-05 18:52:44,086] Trial 4 finished with value: 0.9373857886826906 and parameters: {'learning_rate': 0.02189422965538291, 'max_depth': 3, 'min_samples_leaf': 37, 'l2_regularization': 1.4108161263859986, 'max_bins': 130}. Best is trial 1 with value: 0.9381805118892965.
[I 2026-05-05 18:54:45,079] Trial 5 finished with value: 0.9442576086486953 and parameters: {'learning_rate': 0.04984954840138133, 'max_depth': 4, 'min_samples_leaf': 37, 'l2_regularization': 0.4151877509876112, 'max_bins': 245}. Best is trial 5 with value: 0.9442576086486953.
[I 2026-05-05 18:54:53,353] Trial 2 finished with value: 0.9469034106017903 and parameters: {'learning_rate': 0.14907104037881883, 'max_depth': 8, 'min_samples_leaf': 40, 'l2_regularization': 9.080306192093964, 'max_bins': 178}. Best is trial 2 with value: 0.9469034106017903.
[I 2026-05-05 18:58:05,691] Trial 7 finished with value: 0.9471601601263371 and parameters: {'learning_rate': 0.09694667738182379, 'max_depth': 9, 'min_samples_leaf': 27, 'l2_regularization': 5.26152279629834, 'max_bins': 154}. Best is trial 7 with value: 0.9471601601263371.
[I 2026-05-05 18:58:54,796] Trial 6 pruned.
[I 2026-05-05 18:59:06,302] Trial 3 finished with value: 0.9472476469816856 and parameters: {'learning_rate': 0.09902621587364197, 'max_depth': 10, 'min_samples_leaf': 81, 'l2_regularization': 9.294263879042175, 'max_bins': 240}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 18:59:56,632] Trial 11 pruned.
[I 2026-05-05 19:00:27,259] Trial 9 pruned.
[I 2026-05-05 19:00:46,710] Trial 8 finished with value: 0.9459842079734118 and parameters: {'learning_rate': 0.03126962915279656, 'max_depth': 7, 'min_samples_leaf': 67, 'l2_regularization': 4.000852544439026, 'max_bins': 136}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:00:57,671] Trial 10 pruned.
[I 2026-05-05 19:01:45,551] Trial 0 pruned.
[I 2026-05-05 19:03:25,955] Trial 13 finished with value: 0.9468967998188145 and parameters: {'learning_rate': 0.09532921135883209, 'max_depth': 6, 'min_samples_leaf': 71, 'l2_regularization': 8.8389263663768, 'max_bins': 96}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:03:37,207] Trial 20 pruned.
[I 2026-05-05 19:03:45,616] Trial 18 finished with value: 0.946125807911544 and parameters: {'learning_rate': 0.20787677163986548, 'max_depth': 5, 'min_samples_leaf': 100, 'l2_regularization': 9.278790234561427, 'max_bins': 141}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:04:25,326] Trial 12 finished with value: 0.9471376358207859 and parameters: {'learning_rate': 0.08734629732848476, 'max_depth': 8, 'min_samples_leaf': 89, 'l2_regularization': 7.9008227226872885, 'max_bins': 130}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:04:43,017] Trial 21 finished with value: 0.9459891840285423 and parameters: {'learning_rate': 0.25809887023265, 'max_depth': 10, 'min_samples_leaf': 96, 'l2_regularization': 9.62172461776605, 'max_bins': 76}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:06:26,063] Trial 19 pruned.
[I 2026-05-05 19:06:26,210] Trial 15 finished with value: 0.9469708597188328 and parameters: {'learning_rate': 0.07539848014288085, 'max_depth': 9, 'min_samples_leaf': 40, 'l2_regularization': 1.2184428307347084, 'max_bins': 151}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:06:37,437] Trial 16 finished with value: 0.946901040779116 and parameters: {'learning_rate': 0.11446720496750175, 'max_depth': 8, 'min_samples_leaf': 51, 'l2_regularization': 5.067864771321905, 'max_bins': 174}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:06:50,558] Trial 14 finished with value: 0.9461941031332911 and parameters: {'learning_rate': 0.03945981988182413, 'max_depth': 6, 'min_samples_leaf': 52, 'l2_regularization': 2.226068895399662, 'max_bins': 177}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:07:51,327] Trial 17 pruned.
[I 2026-05-05 19:07:53,777] Trial 24 finished with value: 0.9462329948763568 and parameters: {'learning_rate': 0.22615273959802118, 'max_depth': 10, 'min_samples_leaf': 95, 'l2_regularization': 6.96775944833916, 'max_bins': 193}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:07:55,527] Trial 22 finished with value: 0.946731631644122 and parameters: {'learning_rate': 0.15027011606644955, 'max_depth': 10, 'min_samples_leaf': 90, 'l2_regularization': 9.552671462893962, 'max_bins': 86}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:09:09,044] Trial 23 finished with value: 0.946798458642783 and parameters: {'learning_rate': 0.14145734954780162, 'max_depth': 10, 'min_samples_leaf': 91, 'l2_regularization': 6.925204276263086, 'max_bins': 81}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:14:01,590] Trial 30 finished with value: 0.9468983259217445 and parameters: {'learning_rate': 0.13315419275007437, 'max_depth': 9, 'min_samples_leaf': 82, 'l2_regularization': 6.575355731251242, 'max_bins': 202}. Best is trial 3 with value: 0.9472476469816856.
[I 2026-05-05 19:15:06,775] Trial 26 finished with value: 0.9472618340870836 and parameters: {'learning_rate': 0.08992526781549173, 'max_depth': 10, 'min_samples_leaf': 85, 'l2_regularization': 7.26020271721743, 'max_bins': 210}. Best is trial 26 with value: 0.9472618340870836.
[I 2026-05-05 19:15:51,111] Trial 25 finished with value: 0.9473368825291137 and parameters: {'learning_rate': 0.07955858195496193, 'max_depth': 10, 'min_samples_leaf': 86, 'l2_regularization': 7.321108897602863, 'max_bins': 192}. Best is trial 25 with value: 0.9473368825291137.
[I 2026-05-05 19:16:55,907] Trial 28 finished with value: 0.9471980918964598 and parameters: {'learning_rate': 0.06974926193162781, 'max_depth': 9, 'min_samples_leaf': 84, 'l2_regularization': 6.4166402447291775, 'max_bins': 188}. Best is trial 25 with value: 0.9473368825291137.
[I 2026-05-05 19:17:10,424] Trial 27 finished with value: 0.9473670671909076 and parameters: {'learning_rate': 0.07348770421656471, 'max_depth': 10, 'min_samples_leaf': 81, 'l2_regularization': 6.70145048510531, 'max_bins': 190}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:19:05,681] Trial 29 finished with value: 0.9472224202231528 and parameters: {'learning_rate': 0.06899206536296137, 'max_depth': 9, 'min_samples_leaf': 21, 'l2_regularization': 6.818377676203435, 'max_bins': 190}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:19:27,912] Trial 33 finished with value: 0.947152482772762 and parameters: {'learning_rate': 0.07819228107311131, 'max_depth': 9, 'min_samples_leaf': 83, 'l2_regularization': 7.896436021047313, 'max_bins': 203}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:19:37,156] Trial 32 finished with value: 0.9472636138080907 and parameters: {'learning_rate': 0.06503976916392135, 'max_depth': 9, 'min_samples_leaf': 85, 'l2_regularization': 7.835424920139574, 'max_bins': 200}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:19:38,923] Trial 31 finished with value: 0.9469463264629356 and parameters: {'learning_rate': 0.04892076775387717, 'max_depth': 9, 'min_samples_leaf': 81, 'l2_regularization': 7.4550628563549575, 'max_bins': 204}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:20:22,836] Trial 34 finished with value: 0.9471166661619916 and parameters: {'learning_rate': 0.06727268053785901, 'max_depth': 9, 'min_samples_leaf': 84, 'l2_regularization': 7.882925670640807, 'max_bins': 204}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:20:32,819] Trial 35 finished with value: 0.9472622776211308 and parameters: {'learning_rate': 0.06489735064634448, 'max_depth': 9, 'min_samples_leaf': 79, 'l2_regularization': 7.878823442045446, 'max_bins': 111}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:20:55,138] Trial 36 finished with value: 0.9472242567355208 and parameters: {'learning_rate': 0.07153870671686663, 'max_depth': 9, 'min_samples_leaf': 82, 'l2_regularization': 8.07028846905322, 'max_bins': 115}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:26:25,905] Trial 37 finished with value: 0.9471691092196449 and parameters: {'learning_rate': 0.06976619939569471, 'max_depth': 9, 'min_samples_leaf': 82, 'l2_regularization': 7.960005814678439, 'max_bins': 117}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:27:38,338] Trial 38 finished with value: 0.9472128917196689 and parameters: {'learning_rate': 0.06337763578139191, 'max_depth': 9, 'min_samples_leaf': 80, 'l2_regularization': 8.026276680044415, 'max_bins': 217}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:28:23,329] Trial 39 finished with value: 0.947214096585409 and parameters: {'learning_rate': 0.06485939361724069, 'max_depth': 9, 'min_samples_leaf': 81, 'l2_regularization': 7.900957817793225, 'max_bins': 210}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:28:54,641] Trial 41 finished with value: 0.9468808903724572 and parameters: {'learning_rate': 0.05284572982751474, 'max_depth': 7, 'min_samples_leaf': 77, 'l2_regularization': 7.549136813314348, 'max_bins': 212}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:29:37,487] Trial 40 finished with value: 0.9471843049373211 and parameters: {'learning_rate': 0.054057967027819, 'max_depth': 10, 'min_samples_leaf': 77, 'l2_regularization': 8.217165772315584, 'max_bins': 212}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:31:07,387] Trial 42 finished with value: 0.947123820330831 and parameters: {'learning_rate': 0.05366979749431047, 'max_depth': 10, 'min_samples_leaf': 79, 'l2_regularization': 8.061171846355073, 'max_bins': 209}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:31:16,631] Trial 45 finished with value: 0.9471149573572767 and parameters: {'learning_rate': 0.061451764730319505, 'max_depth': 10, 'min_samples_leaf': 77, 'l2_regularization': 8.354998027744074, 'max_bins': 218}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:31:22,134] Trial 43 finished with value: 0.947040482956722 and parameters: {'learning_rate': 0.05273052419894534, 'max_depth': 10, 'min_samples_leaf': 77, 'l2_regularization': 7.85267283343217, 'max_bins': 218}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:31:23,243] Trial 44 finished with value: 0.9471230175439456 and parameters: {'learning_rate': 0.05341814127946336, 'max_depth': 10, 'min_samples_leaf': 78, 'l2_regularization': 7.9138959910347895, 'max_bins': 219}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:31:30,316] Trial 47 finished with value: 0.9470086619445975 and parameters: {'learning_rate': 0.05645630359218685, 'max_depth': 8, 'min_samples_leaf': 76, 'l2_regularization': 8.510345999853671, 'max_bins': 220}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:31:33,018] Trial 48 finished with value: 0.9470778940959252 and parameters: {'learning_rate': 0.05584622820371906, 'max_depth': 8, 'min_samples_leaf': 76, 'l2_regularization': 5.715358909508638, 'max_bins': 166}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:31:36,223] Trial 46 finished with value: 0.9471200745413624 and parameters: {'learning_rate': 0.05406404228569482, 'max_depth': 10, 'min_samples_leaf': 77, 'l2_regularization': 5.765785897698711, 'max_bins': 214}. Best is trial 27 with value: 0.9473670671909076.
[I 2026-05-05 19:32:06,921] Trial 49 finished with value: 0.9469394300475136 and parameters: {'learning_rate': 0.055362959321905596, 'max_depth': 8, 'min_samples_leaf': 76, 'l2_regularization': 5.714322726724195, 'max_bins': 220}. Best is trial 27 with value: 0.9473670671909076.
Best AUC: 0.9473670671909076
Best params: {'learning_rate': 0.07348770421656471, 'max_depth': 10, 'min_samples_leaf': 81, 'l2_regularization': 6.70145048510531, 'max_bins': 190}

In [19]:
model_tuned = HistGradientBoostingClassifier(
    max_iter=1000,
    early_stopping=True,
    validation_fraction=0.1,
    n_iter_no_change=50,
    random_state=42,
    **study.best_params
)

pipe_tuned = Pipeline([('drop_feat', drop_feat), ('hist', model_tuned)])
pipe_tuned.fit(X_train, y_train.PitNextLap)

Pipeline(steps=[('drop_feat',
                 DropFeatures(features_to_drop=['remainder__raceprogress_high',
                                                'remainder__lapnumber_high',
                                                'remainder__position_high',
                                                'remainder__laptime_s_high',
                                                'remainder__position_norm',
                                                'remainder__stint_high',
                                                'remainder__is_pit_lap',
                                                'remainder__lapnumber_low'])),
                ('hist',
                 HistGradientBoostingClassifier(early_stopping=True,
                                                l2_regularization=6.70145048510531,
                                                learning_rate=0.07348770421656471,
                                                max_bins=190, max_depth=10,
                                                max_iter=1000,
                                                min_samples_leaf=81,
                                                n_iter_no_change=50,
                                                random_state=42))])

# Deploy

In [20]:
dump_pickle(pipe_tuned, '../models/model_histgradientboosting.pkl')